// default package
// Generated Jun 15, 2016 5:39:06 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;
import java.util.HashSet;
import java.util.Set;

/**
 * MaCustomer generated by hbm2java
 */
public class MaCustomer implements java.io.Serializable {

	//private int customerId; I am going to change this bc of previous problems (and all the related methods...)
	private Integer customerId;
	private String customerCode;
	private String cuatomerName;
	private String customerDspName;
	private String customerTel;
	private String customerFax;
	private String customerTantoName;
	private String customerEmailAddrs;
	private Set tzPrjs = new HashSet(0);

	public MaCustomer() {
	}

	public MaCustomer(Integer customerId, String customerCode, String cuatomerName, String customerDspName,
			String customerTel, String customerFax, String customerTantoName, String customerEmailAddrs) {
		this.customerId = customerId;
		this.customerCode = customerCode;
		this.cuatomerName = cuatomerName;
		this.customerDspName = customerDspName;
		this.customerTel = customerTel;
		this.customerFax = customerFax;
		this.customerTantoName = customerTantoName;
		this.customerEmailAddrs = customerEmailAddrs;
	}

	public MaCustomer(Integer customerId, String customerCode, String cuatomerName, String customerDspName,
			String customerTel, String customerFax, String customerTantoName, String customerEmailAddrs, Set tzPrjs) {
		this.customerId = customerId;
		this.customerCode = customerCode;
		this.cuatomerName = cuatomerName;
		this.customerDspName = customerDspName;
		this.customerTel = customerTel;
		this.customerFax = customerFax;
		this.customerTantoName = customerTantoName;
		this.customerEmailAddrs = customerEmailAddrs;
		this.tzPrjs = tzPrjs;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	public String getCuatomerName() {
		return this.cuatomerName;
	}

	public void setCuatomerName(String cuatomerName) {
		this.cuatomerName = cuatomerName;
	}

	public String getCustomerDspName() {
		return this.customerDspName;
	}

	public void setCustomerDspName(String customerDspName) {
		this.customerDspName = customerDspName;
	}

	public String getCustomerTel() {
		return this.customerTel;
	}

	public void setCustomerTel(String customerTel) {
		this.customerTel = customerTel;
	}

	public String getCustomerFax() {
		return this.customerFax;
	}

	public void setCustomerFax(String customerFax) {
		this.customerFax = customerFax;
	}

	public String getCustomerTantoName() {
		return this.customerTantoName;
	}

	public void setCustomerTantoName(String customerTantoName) {
		this.customerTantoName = customerTantoName;
	}

	public String getCustomerEmailAddrs() {
		return this.customerEmailAddrs;
	}

	public void setCustomerEmailAddrs(String customerEmailAddrs) {
		this.customerEmailAddrs = customerEmailAddrs;
	}

	public Set getTzPrjs() {
		return this.tzPrjs;
	}

	public void setTzPrjs(Set tzPrjs) {
		this.tzPrjs = tzPrjs;
	}

	@Override
	public String toString() {
		return "MaCustomer [customerId=" + customerId + ", customerCode=" + customerCode + ", cuatomerName="
				+ cuatomerName + ", customerDspName=" + customerDspName + ", customerTel=" + customerTel
				+ ", customerFax=" + customerFax + ", customerTantoName=" + customerTantoName + ", customerEmailAddrs="
				+ customerEmailAddrs +  "]";
	}

}
