// default package
// Generated Jun 15, 2016 5:39:06 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MaEngineerkbn generated by hbm2java
 */
public class MaEngineerkbn implements java.io.Serializable {

	private Integer engineerkbnId;
	private String engineerkbnCode;
	private String engineerkbnName;
	private Date creDtime;
	private Date updDtime;
	private String maEngineerkbncol;
	private Set tzPrjNeedsEngineers = new HashSet(0);

	public MaEngineerkbn() {
	}

	public MaEngineerkbn(Integer engineerkbnId) {
		this.engineerkbnId = engineerkbnId;
	}

	public MaEngineerkbn(Integer engineerkbnId, String engineerkbnCode, String engineerkbnName, Date creDtime,
			Date updDtime, String maEngineerkbncol, Set tzPrjNeedsEngineers) {
		this.engineerkbnId = engineerkbnId;
		this.engineerkbnCode = engineerkbnCode;
		this.engineerkbnName = engineerkbnName;
		this.creDtime = creDtime;
		this.updDtime = updDtime;
		this.maEngineerkbncol = maEngineerkbncol;
		this.tzPrjNeedsEngineers = tzPrjNeedsEngineers;
	}

	public Integer getEngineerkbnId() {
		return this.engineerkbnId;
	}

	public void setEngineerkbnId(Integer engineerkbnId) {
		this.engineerkbnId = engineerkbnId;
	}

	public String getEngineerkbnCode() {
		return this.engineerkbnCode;
	}

	public void setEngineerkbnCode(String engineerkbnCode) {
		this.engineerkbnCode = engineerkbnCode;
	}

	public String getEngineerkbnName() {
		return this.engineerkbnName;
	}

	public void setEngineerkbnName(String engineerkbnName) {
		this.engineerkbnName = engineerkbnName;
	}

	public Date getCreDtime() {
		return this.creDtime;
	}

	public void setCreDtime(Date creDtime) {
		this.creDtime = creDtime;
	}

	public Date getUpdDtime() {
		return this.updDtime;
	}

	public void setUpdDtime(Date updDtime) {
		this.updDtime = updDtime;
	}

	public String getMaEngineerkbncol() {
		return this.maEngineerkbncol;
	}

	public void setMaEngineerkbncol(String maEngineerkbncol) {
		this.maEngineerkbncol = maEngineerkbncol;
	}

	public Set getTzPrjNeedsEngineers() {
		return this.tzPrjNeedsEngineers;
	}

	public void setTzPrjNeedsEngineers(Set tzPrjNeedsEngineers) {
		this.tzPrjNeedsEngineers = tzPrjNeedsEngineers;
	}

}
