// default package
// Generated Jun 15, 2016 5:39:06 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * MaSkillitemId generated by hbm2java
 */


public class MaSkillitemId implements java.io.Serializable {
	
	private static final Logger log = LogManager.getLogger(MaSkillitemId.class);	

	private String categoryCode;
	private String skillCode;

	public MaSkillitemId() {
	}

	public MaSkillitemId(String categoryCode, String skillCode) {
		this.categoryCode = categoryCode;
		this.skillCode = skillCode;
	}

	public String getCategoryCode() {
		return this.categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public String getSkillCode() {
		return this.skillCode;
	}

	public void setSkillCode(String skillCode) {
		this.skillCode = skillCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MaSkillitemId))
			return false;
		MaSkillitemId castOther = (MaSkillitemId) other;

		return ((this.getCategoryCode() == castOther.getCategoryCode()) || (this.getCategoryCode() != null
				&& castOther.getCategoryCode() != null && this.getCategoryCode().equals(castOther.getCategoryCode())))
				&& ((this.getSkillCode() == castOther.getSkillCode()) || (this.getSkillCode() != null
						&& castOther.getSkillCode() != null && this.getSkillCode().equals(castOther.getSkillCode())));
	}
	
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCategoryCode() == null ? 0 : this.getCategoryCode().hashCode());
		result = 37 * result + (getSkillCode() == null ? 0 : this.getSkillCode().hashCode());
		log.debug("============ hashCode in MaSkillitemId returns: "+result);
		return result;
	}

}
