// default package
// Generated Jul 7, 2016 5:11:45 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * MaSkillitem generated by hbm2java
 */
package co.jp.eureka.entities;

public class MaSkillitem implements java.io.Serializable {

	private String skillCode;
	private MaSkillcategory maSkillcategory;
	private String skillName;
	private int skillDspOrder;
	private String prjNeedsSkillId;
	
private Integer skillLevel;
	
	
	public Integer getSkillLevel() {
		return skillLevel;
	}

	public void setSkillLevel(Integer skillLevel) {
		this.skillLevel = skillLevel;
	}

	public MaSkillitem() {
	}

	public MaSkillitem(String skillCode, MaSkillcategory maSkillcategory, String skillName, int skillDspOrder) {
		this.skillCode = skillCode;
		this.maSkillcategory = maSkillcategory;
		this.skillName = skillName;
		this.skillDspOrder = skillDspOrder;
	}

	public MaSkillitem(String skillCode, MaSkillcategory maSkillcategory, String skillName, int skillDspOrder,
			String prjNeedsSkillId) {
		this.skillCode = skillCode;
		this.maSkillcategory = maSkillcategory;
		this.skillName = skillName;
		this.skillDspOrder = skillDspOrder;
		this.prjNeedsSkillId = prjNeedsSkillId;
	}

	public String getSkillCode() {
		return this.skillCode;
	}

	public void setSkillCode(String skillCode) {
		this.skillCode = skillCode;
	}

	public MaSkillcategory getMaSkillcategory() {
		return this.maSkillcategory;
	}

	public void setMaSkillcategory(MaSkillcategory maSkillcategory) {
		this.maSkillcategory = maSkillcategory;
	}

	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public int getSkillDspOrder() {
		return this.skillDspOrder;
	}

	public void setSkillDspOrder(int skillDspOrder) {
		this.skillDspOrder = skillDspOrder;
	}

	public String getPrjNeedsSkillId() {
		return this.prjNeedsSkillId;
	}

	public void setPrjNeedsSkillId(String prjNeedsSkillId) {
		this.prjNeedsSkillId = prjNeedsSkillId;
	}

}
