// default package
// Generated Jun 15, 2016 5:39:06 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;
import java.util.HashSet;
import java.util.Set;

/**
 * MaSkillcategory generated by hbm2java
 */
public class MaSkillcategory implements java.io.Serializable {

	private String categoryCodecode;
	private String categoryName;
	private Integer categoryDspOrder;
	
	
	

	private Set tzPrjNeedsSkills = new HashSet(0);

	public MaSkillcategory() {
	}

	public MaSkillcategory(String categoryCode, String categoryName, Integer categoryDspOrder) {
		this.categoryCodecode = categoryCode;
		this.categoryName = categoryName;
		this.categoryDspOrder = categoryDspOrder;
	}

	public MaSkillcategory(String categoryCode, String categoryName, Integer categoryDspOrder, Set tzPrjNeedsSkills) {
		this.categoryCodecode = categoryCode;
		this.categoryName = categoryName;
		this.categoryDspOrder = categoryDspOrder;
		this.tzPrjNeedsSkills = tzPrjNeedsSkills;
	}

	// Not all the fields 
	@Override
	public String toString() {
		return "MaSkillcategory [categoryCodecode=" + categoryCodecode + ", categoryName=" + categoryName
				+ ", categoryDspOrder=" + categoryDspOrder + "]";
	}
	
	public String getCategoryCodecode() {
		return this.categoryCodecode;
	}

	public void setCategoryCodecode(String categoryCode) {
		this.categoryCodecode = categoryCode;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public Integer getCategoryDspOrder() {
		return this.categoryDspOrder;
	}

	public void setCategoryDspOrder(Integer categoryDspOrder) {
		this.categoryDspOrder = categoryDspOrder;
	}

	public Set getTzPrjNeedsSkills() {
		return this.tzPrjNeedsSkills;
	}

	public void setTzPrjNeedsSkills(Set tzPrjNeedsSkills) {
		this.tzPrjNeedsSkills = tzPrjNeedsSkills;
	}

}
