// default package
// Generated Jun 15, 2016 5:39:06 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;
import java.util.Date;

/**
 * TzPrjNeedsSkill generated by hbm2java
 */
public class TzPrjNeedsSkill_old implements java.io.Serializable {

	

	private TzPrjNeedsSkillId id;
	private MaSkillcategory maSkillcategory;
	private MaSkillitem maSkillitem;
	private TzPrj tzPrj;
	private TzPrjNeedsEngineer tzPrjNeedsEngineer;
	private String prjNeedsSkillCode;//mine
	
	//mis getter and setter
	public String getPrjNeedsSkillCode() {
		return prjNeedsSkillCode;
	}

	public void setPrjNeedsSkillCode(String prjNeedsSkillCode) {
		this.prjNeedsSkillCode = prjNeedsSkillCode;
	}

	private Integer prjNeedsSkillLevel;
	private Integer prjNeedsSkillUpdKaishaId;
	private Integer prjNeedsSkillUpdUserId;
	private Date updDtime;

	public TzPrjNeedsSkill_old() {
	}

	public TzPrjNeedsSkill_old(MaSkillcategory maSkillcategory, MaSkillitem maSkillitem, TzPrj tzPrj,
			TzPrjNeedsEngineer tzPrjNeedsEngineer,
			String prjNeedsSkillCode, //mio
			Integer prjNeedsSkillLevel, Integer prjNeedsSkillUpdKaishaId,
			Integer prjNeedsSkillUpdUserId, Date updDtime) {
		this.maSkillcategory = maSkillcategory;
		this.maSkillitem = maSkillitem;
		this.tzPrj = tzPrj;
		this.tzPrjNeedsEngineer = tzPrjNeedsEngineer;
		this.prjNeedsSkillCode=prjNeedsSkillCode; //mio
		this.prjNeedsSkillLevel = prjNeedsSkillLevel;
		this.prjNeedsSkillUpdKaishaId = prjNeedsSkillUpdKaishaId;
		this.prjNeedsSkillUpdUserId = prjNeedsSkillUpdUserId;
		this.updDtime = updDtime;
	}

	public TzPrjNeedsSkillId getId() {
		return this.id;
	}

	public void setId(TzPrjNeedsSkillId id) {
		this.id = id;
	}

	public MaSkillcategory getMaSkillcategory() {
		return this.maSkillcategory;
	}

	public void setMaSkillcategory(MaSkillcategory maSkillcategory) {
		this.maSkillcategory = maSkillcategory;
	}

	public MaSkillitem getMaSkillitem() {
		return this.maSkillitem;
	}

	public void setMaSkillitem(MaSkillitem maSkillitem) {
		this.maSkillitem = maSkillitem;
	}

	public TzPrj getTzPrj() {
		return this.tzPrj;
	}

	public void setTzPrj(TzPrj tzPrj) {
		this.tzPrj = tzPrj;
	}

	public TzPrjNeedsEngineer getTzPrjNeedsEngineer() {
		return this.tzPrjNeedsEngineer;
	}

	public void setTzPrjNeedsEngineer(TzPrjNeedsEngineer tzPrjNeedsEngineer) {
		this.tzPrjNeedsEngineer = tzPrjNeedsEngineer;
	}

	public Integer getPrjNeedsSkillLevel() {
		return this.prjNeedsSkillLevel;
	}

	public void setPrjNeedsSkillLevel(Integer prjNeedsSkillLevel) {
		this.prjNeedsSkillLevel = prjNeedsSkillLevel;
	}

	public Integer getPrjNeedsSkillUpdKaishaId() {
		return this.prjNeedsSkillUpdKaishaId;
	}

	public void setPrjNeedsSkillUpdKaishaId(Integer prjNeedsSkillUpdKaishaId) {
		this.prjNeedsSkillUpdKaishaId = prjNeedsSkillUpdKaishaId;
	}

	public Integer getPrjNeedsSkillUpdUserId() {
		return this.prjNeedsSkillUpdUserId;
	}

	public void setPrjNeedsSkillUpdUserId(Integer prjNeedsSkillUpdUserId) {
		this.prjNeedsSkillUpdUserId = prjNeedsSkillUpdUserId;
	}

	public Date getUpdDtime() {
		return this.updDtime;
	}

	public void setUpdDtime(Date updDtime) {
		this.updDtime = updDtime;
	}
	//I did (Cano)
	@Override
	public String toString() {
		return "TzPrjNeedsSkill [id=" + id.getPrjId()+":"+id.getPrjSubId()+":"+id.getTzPrjNeedsEngineerkbnId() + ", maSkillcategory=" + maSkillcategory + ", maSkillitem=" + maSkillitem
				+ ", tzPrj=" + tzPrj + ", tzPrjNeedsEngineer=" + tzPrjNeedsEngineer + ", prjNeedsSkillCode="
				+ prjNeedsSkillCode + ", prjNeedsSkillLevel=" + prjNeedsSkillLevel + ", prjNeedsSkillUpdKaishaId="
				+ prjNeedsSkillUpdKaishaId + ", prjNeedsSkillUpdUserId=" + prjNeedsSkillUpdUserId + ", updDtime="
				+ updDtime + "]";
	}

}
