// default package
// Generated Jun 15, 2016 5:39:06 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;
import java.util.Date;

/**
 * TzPrjNeedsEngineer generated by hbm2java
 */
public class TzPrjNeedsEngineer implements java.io.Serializable {

	private TzPrjNeedsEngineerId id;
	private MaEngineerkbn maEngineerkbn;
	private Integer prjNeedsEngineerNumber;
	private Date prjNeedsPriodFrom;
	private Date prjNeedsPriodTo;
	private Integer prjNeedsEngineerRoughPrice;
	private String prjNeedsEngineerWorkingPlace;
	private String prjNeedsEngineerEtc;
	private Integer prjNeedsEngineerUpdKaishaId;
	private Integer prjNeedsEngineerUpdUserId;
	private Date updDtime;
	private TzPrjNeedsSkill tzPrjNeedsSkill;

	public TzPrjNeedsEngineer() {
	}

	public TzPrjNeedsEngineer(TzPrjNeedsEngineerId id, MaEngineerkbn maEngineerkbn, Integer prjNeedsEngineerNumber,
			Date prjNeedsPriodFrom, Integer prjNeedsEngineerRoughPrice, String prjNeedsEngineerWorkingPlace,
			String prjNeedsEngineerEtc, Integer prjNeedsEngineerUpdKaishaId, Integer prjNeedsEngineerUpdUserId, Date updDtime) {
		this.id = id;
		this.maEngineerkbn = maEngineerkbn;
		this.prjNeedsEngineerNumber = prjNeedsEngineerNumber;
		this.prjNeedsPriodFrom = prjNeedsPriodFrom;
		this.prjNeedsEngineerRoughPrice = prjNeedsEngineerRoughPrice;
		this.prjNeedsEngineerWorkingPlace = prjNeedsEngineerWorkingPlace;
		this.prjNeedsEngineerEtc = prjNeedsEngineerEtc;
		this.prjNeedsEngineerUpdKaishaId = prjNeedsEngineerUpdKaishaId;
		this.prjNeedsEngineerUpdUserId = prjNeedsEngineerUpdUserId;
		this.updDtime = updDtime;
	}

	public TzPrjNeedsEngineer(TzPrjNeedsEngineerId id, MaEngineerkbn maEngineerkbn, Integer prjNeedsEngineerNumber,
			Date prjNeedsPriodFrom, Date prjNeedsPriodTo, Integer prjNeedsEngineerRoughPrice,
			String prjNeedsEngineerWorkingPlace, String prjNeedsEngineerEtc, Integer prjNeedsEngineerUpdKaishaId,
			Integer prjNeedsEngineerUpdUserId, Date updDtime, TzPrjNeedsSkill tzPrjNeedsSkill) {
		this.id = id;
		this.maEngineerkbn = maEngineerkbn;
		this.prjNeedsEngineerNumber = prjNeedsEngineerNumber;
		this.prjNeedsPriodFrom = prjNeedsPriodFrom;
		this.prjNeedsPriodTo = prjNeedsPriodTo;
		this.prjNeedsEngineerRoughPrice = prjNeedsEngineerRoughPrice;
		this.prjNeedsEngineerWorkingPlace = prjNeedsEngineerWorkingPlace;
		this.prjNeedsEngineerEtc = prjNeedsEngineerEtc;
		this.prjNeedsEngineerUpdKaishaId = prjNeedsEngineerUpdKaishaId;
		this.prjNeedsEngineerUpdUserId = prjNeedsEngineerUpdUserId;
		this.updDtime = updDtime;
		this.tzPrjNeedsSkill = tzPrjNeedsSkill;
	}

	public TzPrjNeedsEngineerId getId() {
		return this.id;
	}

	public void setId(TzPrjNeedsEngineerId id) {
		this.id = id;
	}

	public MaEngineerkbn getMaEngineerkbn() {
		return this.maEngineerkbn;
	}

	public void setMaEngineerkbn(MaEngineerkbn maEngineerkbn) {
		this.maEngineerkbn = maEngineerkbn;
	}

	public Integer getPrjNeedsEngineerNumber() {
		return this.prjNeedsEngineerNumber;
	}

	public void setPrjNeedsEngineerNumber(Integer prjNeedsEngineerNumber) {
		this.prjNeedsEngineerNumber = prjNeedsEngineerNumber;
	}

	public Date getPrjNeedsPriodFrom() {
		return this.prjNeedsPriodFrom;
	}

	public void setPrjNeedsPriodFrom(Date prjNeedsPriodFrom) {
		this.prjNeedsPriodFrom = prjNeedsPriodFrom;
	}

	public Date getPrjNeedsPriodTo() {
		return this.prjNeedsPriodTo;
	}

	public void setPrjNeedsPriodTo(Date prjNeedsPriodTo) {
		this.prjNeedsPriodTo = prjNeedsPriodTo;
	}

	public Integer getPrjNeedsEngineerRoughPrice() {
		return this.prjNeedsEngineerRoughPrice;
	}

	public void setPrjNeedsEngineerRoughPrice(Integer prjNeedsEngineerRoughPrice) {
		this.prjNeedsEngineerRoughPrice = prjNeedsEngineerRoughPrice;
	}

	public String getPrjNeedsEngineerWorkingPlace() {
		return this.prjNeedsEngineerWorkingPlace;
	}

	public void setPrjNeedsEngineerWorkingPlace(String prjNeedsEngineerWorkingPlace) {
		this.prjNeedsEngineerWorkingPlace = prjNeedsEngineerWorkingPlace;
	}

	public String getPrjNeedsEngineerEtc() {
		return this.prjNeedsEngineerEtc;
	}

	public void setPrjNeedsEngineerEtc(String prjNeedsEngineerEtc) {
		this.prjNeedsEngineerEtc = prjNeedsEngineerEtc;
	}

	public Integer getPrjNeedsEngineerUpdKaishaId() {
		return this.prjNeedsEngineerUpdKaishaId;
	}

	public void setPrjNeedsEngineerUpdKaishaId(Integer prjNeedsEngineerUpdKaishaId) {
		this.prjNeedsEngineerUpdKaishaId = prjNeedsEngineerUpdKaishaId;
	}

	public Integer getPrjNeedsEngineerUpdUserId() {
		return this.prjNeedsEngineerUpdUserId;
	}

	public void setPrjNeedsEngineerUpdUserId(Integer prjNeedsEngineerUpdUserId) {
		this.prjNeedsEngineerUpdUserId = prjNeedsEngineerUpdUserId;
	}

	public Date getUpdDtime() {
		return this.updDtime;
	}

	public void setUpdDtime(Date updDtime) {
		this.updDtime = updDtime;
	}

	public TzPrjNeedsSkill getTzPrjNeedsSkill() {
		return this.tzPrjNeedsSkill;
	}

	public void setTzPrjNeedsSkill(TzPrjNeedsSkill tzPrjNeedsSkill) {
		this.tzPrjNeedsSkill = tzPrjNeedsSkill;
	}

}
