// default package
// Generated Jul 7, 2016 5:11:45 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;
import java.util.Date;

/**
 * TzPrjNeedsSkill generated by hbm2java
 */
public class TzPrjNeedsSkill implements java.io.Serializable {

	private TzPrjNeedsSkillId id;
	private TzPrj tzPrj;
//	private TzPrjNeedsEngineer tzPrjNeedsEngineerByPrjId;
//	private TzPrjNeedsEngineer tzPrjNeedsEngineerByPrjSubId;
//	private TzPrjNeedsEngineer tzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId;
	// Above changed for this (1 row):
	private TzPrjNeedsEngineer tzPrjNeedsEngineer;
	
	private int prjNeedsSkillUpdKaishaId;
	private int prjNeedsSkillUpdUserId;
	private Date updDtime;

	public TzPrjNeedsSkill() {
	}

//	public TzPrjNeedsSkill(TzPrjNeedsSkillId id, TzPrj tzPrj, TzPrjNeedsEngineer tzPrjNeedsEngineerByPrjId,
//			TzPrjNeedsEngineer tzPrjNeedsEngineerByPrjSubId,
//			TzPrjNeedsEngineer tzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId, int prjNeedsSkillUpdKaishaId,
//			int prjNeedsSkillUpdUserId, Date updDtime) {
	
	public TzPrjNeedsSkill(TzPrjNeedsSkillId id, TzPrj tzPrj, TzPrjNeedsEngineer tzPrjNeedsEngineer,
			int prjNeedsSkillUpdKaishaId,
			int prjNeedsSkillUpdUserId, Date updDtime) {
		this.id = id;
		this.tzPrj = tzPrj;
//		this.tzPrjNeedsEngineerByPrjId = tzPrjNeedsEngineerByPrjId;
//		this.tzPrjNeedsEngineerByPrjSubId = tzPrjNeedsEngineerByPrjSubId;
//		this.tzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId = tzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId;
		this.tzPrjNeedsEngineer = tzPrjNeedsEngineer;
		this.prjNeedsSkillUpdKaishaId = prjNeedsSkillUpdKaishaId;
		this.prjNeedsSkillUpdUserId = prjNeedsSkillUpdUserId;
		this.updDtime = updDtime;
	}
	
	public TzPrjNeedsEngineer getTzPrjNeedsEngineer() {
		return this.tzPrjNeedsEngineer;
	}

	public void setTzPrjNeedsEngineer(TzPrjNeedsEngineer tzPrjNeedsEngineer) {
		this.tzPrjNeedsEngineer = tzPrjNeedsEngineer;
	}

	public TzPrjNeedsSkillId getId() {
		return this.id;
	}

	public void setId(TzPrjNeedsSkillId id) {
		this.id = id;
	}

	public TzPrj getTzPrj() {
		return this.tzPrj;
	}

	public void setTzPrj(TzPrj tzPrj) {
		this.tzPrj = tzPrj;
	}

//	public TzPrjNeedsEngineer getTzPrjNeedsEngineerByPrjId() {
//		return this.tzPrjNeedsEngineerByPrjId;
//	}
//
//	public void setTzPrjNeedsEngineerByPrjId(TzPrjNeedsEngineer tzPrjNeedsEngineerByPrjId) {
//		this.tzPrjNeedsEngineerByPrjId = tzPrjNeedsEngineerByPrjId;
//	}
//
//	public TzPrjNeedsEngineer getTzPrjNeedsEngineerByPrjSubId() {
//		return this.tzPrjNeedsEngineerByPrjSubId;
//	}
//
//	public void setTzPrjNeedsEngineerByPrjSubId(TzPrjNeedsEngineer tzPrjNeedsEngineerByPrjSubId) {
//		this.tzPrjNeedsEngineerByPrjSubId = tzPrjNeedsEngineerByPrjSubId;
//	}
//
//	public TzPrjNeedsEngineer getTzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId() {
//		return this.tzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId;
//	}
//
//	public void setTzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId(
//			TzPrjNeedsEngineer tzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId) {
//		this.tzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId = tzPrjNeedsEngineerByTzPrjNeedsEngineerkbnId;
//	}

	public int getPrjNeedsSkillUpdKaishaId() {
		return this.prjNeedsSkillUpdKaishaId;
	}

	public void setPrjNeedsSkillUpdKaishaId(int prjNeedsSkillUpdKaishaId) {
		this.prjNeedsSkillUpdKaishaId = prjNeedsSkillUpdKaishaId;
	}

	public int getPrjNeedsSkillUpdUserId() {
		return this.prjNeedsSkillUpdUserId;
	}

	public void setPrjNeedsSkillUpdUserId(int prjNeedsSkillUpdUserId) {
		this.prjNeedsSkillUpdUserId = prjNeedsSkillUpdUserId;
	}

	public Date getUpdDtime() {
		return this.updDtime;
	}

	public void setUpdDtime(Date updDtime) {
		this.updDtime = updDtime;
	}

}
