// default package
// Generated Jun 15, 2016 5:39:06 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TzPrj generated by hbm2java
 */
public class TzPrj implements java.io.Serializable {

	private Integer prId;  //nn PK auto (fron int to Integer bc Hibernate was complaining..)
	private MaCustomer maCustomer; //needed in order to save a record..  (because is a not null record in DB)
	private MaProjectkbn maProjectkbn; //needed in order to save a record.. (because is a not null record in DB) 
	private Integer prjKbnId; //nn
	private Integer prjImportanceId; //nn
	private Integer prjTargetId; //nn  (bool)
	private Integer prjProfitabilityId; //nn (bool)
	private Integer prjNearshoreId; //nn (bool)
	private Integer prjStrategicId; //nn  (bool)
	private String prjEnduserName; //ny 
	private String prjName; //nn
	private String prjSummary; //nn
	private String prjWorkingPlace; //ny
	private Date prjDeliveryDate; //ny
	private String prjSecurityRequirements; //ny
	private String prjEtcRequirements; //ny
	private String prjEtc;  //ny
	private Integer prjSalesKaishaId;  //..ny
	private Integer prjAddUserId;   //nn
	private Integer prjUpdKaishaId; //nn
	private Integer prjUpdUserId; //nn
	private Date creDtime; //nn
	private Date updDtime; //nn
	private Set tzPrjNeedsSkills = new HashSet(0);  

	public TzPrj() {
	}

	public TzPrj(MaCustomer maCustomer, MaProjectkbn maProjectkbn, Integer prjKbnId, Integer prjImportanceId, Integer prjTargetId,
			Integer prjProfitabilityId, Integer prjNearshoreId, Integer prjStrategicId, String prjName, String prjSummary,
			Integer prjAddUserId, Integer prjUpdKaishaId, Integer prjUpdUserId, Date creDtime, Date updDtime) {
		this.maCustomer = maCustomer;
		this.maProjectkbn = maProjectkbn;
		this.prjKbnId = prjKbnId;
		this.prjImportanceId = prjImportanceId;
		this.prjTargetId = prjTargetId;
		this.prjProfitabilityId = prjProfitabilityId;
		this.prjNearshoreId = prjNearshoreId;
		this.prjStrategicId = prjStrategicId;
		this.prjName = prjName;
		this.prjSummary = prjSummary;
		this.prjAddUserId = prjAddUserId;
		this.prjUpdKaishaId = prjUpdKaishaId;
		this.prjUpdUserId = prjUpdUserId;
		this.creDtime = creDtime;
		this.updDtime = updDtime;
	}

	public TzPrj(MaCustomer maCustomer, MaProjectkbn maProjectkbn, Integer prjKbnId, Integer prjImportanceId, Integer prjTargetId,
			Integer prjProfitabilityId, Integer prjNearshoreId, Integer prjStrategicId, String prjEnduserName, String prjName,
			String prjSummary, String prjWorkingPlace, Date prjDeliveryDate, String prjSecurityRequirements,
			String prjEtcRequirements, String prjEtc, Integer prjSalesKaishaId, Integer prjAddUserId, Integer prjUpdKaishaId,
			Integer prjUpdUserId, Date creDtime, Date updDtime, Set tzPrjNeedsSkills) {
		this.maCustomer = maCustomer;
		this.maProjectkbn = maProjectkbn;
		this.prjKbnId = prjKbnId;
		this.prjImportanceId = prjImportanceId;
		this.prjTargetId = prjTargetId;
		this.prjProfitabilityId = prjProfitabilityId;
		this.prjNearshoreId = prjNearshoreId;
		this.prjStrategicId = prjStrategicId;
		this.prjEnduserName = prjEnduserName;
		this.prjName = prjName;
		this.prjSummary = prjSummary;
		this.prjWorkingPlace = prjWorkingPlace;
		this.prjDeliveryDate = prjDeliveryDate;
		this.prjSecurityRequirements = prjSecurityRequirements;
		this.prjEtcRequirements = prjEtcRequirements;
		this.prjEtc = prjEtc;
		this.prjSalesKaishaId = prjSalesKaishaId;
		this.prjAddUserId = prjAddUserId;
		this.prjUpdKaishaId = prjUpdKaishaId;
		this.prjUpdUserId = prjUpdUserId;
		this.creDtime = creDtime;
		this.updDtime = updDtime;
		this.tzPrjNeedsSkills = tzPrjNeedsSkills;
	}

	public Integer getPrId() {
		return this.prId;
	}

	public void setPrId(Integer prId) {
		this.prId = prId;
	}

	public MaCustomer getMaCustomer() {
		return this.maCustomer;
	}

	public void setMaCustomer(MaCustomer maCustomer) {
		this.maCustomer = maCustomer;
	}

	public MaProjectkbn getMaProjectkbn() {
		return this.maProjectkbn;
	}

	public void setMaProjectkbn(MaProjectkbn maProjectkbn) {
		this.maProjectkbn = maProjectkbn;
	}

	public Integer getPrjKbnId() {
		return this.prjKbnId;
	}

	public void setPrjKbnId(Integer prjKbnId) {
		this.prjKbnId = prjKbnId;
	}

	public Integer getPrjImportanceId() {
		return this.prjImportanceId;
	}

	public void setPrjImportanceId(Integer prjImportanceId) {
		this.prjImportanceId = prjImportanceId;
	}

	public Integer getPrjTargetId() {
		return this.prjTargetId;
	}

	public void setPrjTargetId(Integer prjTargetId) {
		this.prjTargetId = prjTargetId;
	}

	public Integer getPrjProfitabilityId() {
		return this.prjProfitabilityId;
	}

	public void setPrjProfitabilityId(Integer prjProfitabilityId) {
		this.prjProfitabilityId = prjProfitabilityId;
	}

	public Integer getPrjNearshoreId() {
		return this.prjNearshoreId;
	}

	public void setPrjNearshoreId(Integer prjNearshoreId) {
		this.prjNearshoreId = prjNearshoreId;
	}

	public Integer getPrjStrategicId() {
		return this.prjStrategicId;
	}

	public void setPrjStrategicId(Integer prjStrategicId) {
		this.prjStrategicId = prjStrategicId;
	}

	public String getPrjEnduserName() {
		return this.prjEnduserName;
	}

	public void setPrjEnduserName(String prjEnduserName) {
		this.prjEnduserName = prjEnduserName;
	}

	public String getPrjName() {
		return this.prjName;
	}

	public void setPrjName(String prjName) {
		this.prjName = prjName;
	}

	public String getPrjSummary() {
		return this.prjSummary;
	}

	public void setPrjSummary(String prjSummary) {
		this.prjSummary = prjSummary;
	}

	public String getPrjWorkingPlace() {
		return this.prjWorkingPlace;
	}

	public void setPrjWorkingPlace(String prjWorkingPlace) {
		this.prjWorkingPlace = prjWorkingPlace;
	}

	public Date getPrjDeliveryDate() {
		return this.prjDeliveryDate;
	}

	public void setPrjDeliveryDate(Date prjDeliveryDate) {
		this.prjDeliveryDate = prjDeliveryDate;
	}

	public String getPrjSecurityRequirements() {
		return this.prjSecurityRequirements;
	}

	public void setPrjSecurityRequirements(String prjSecurityRequirements) {
		this.prjSecurityRequirements = prjSecurityRequirements;
	}

	public String getPrjEtcRequirements() {
		return this.prjEtcRequirements;
	}

	public void setPrjEtcRequirements(String prjEtcRequirements) {
		this.prjEtcRequirements = prjEtcRequirements;
	}

	public String getPrjEtc() {
		return this.prjEtc;
	}

	public void setPrjEtc(String prjEtc) {
		this.prjEtc = prjEtc;
	}

	public Integer getPrjSalesKaishaId() {
		return this.prjSalesKaishaId;
	}

	public void setPrjSalesKaishaId(Integer prjSalesKaishaId) {
		this.prjSalesKaishaId = prjSalesKaishaId;
	}

	public Integer getPrjAddUserId() {
		return this.prjAddUserId;
	}

	public void setPrjAddUserId(Integer prjAddUserId) {
		this.prjAddUserId = prjAddUserId;
	}

	public Integer getPrjUpdKaishaId() {
		return this.prjUpdKaishaId;
	}

	public void setPrjUpdKaishaId(Integer prjUpdKaishaId) {
		this.prjUpdKaishaId = prjUpdKaishaId;
	}

	public Integer getPrjUpdUserId() {
		return this.prjUpdUserId;
	}

	public void setPrjUpdUserId(Integer prjUpdUserId) {
		this.prjUpdUserId = prjUpdUserId;
	}

	public Date getCreDtime() {
		return this.creDtime;
	}

	public void setCreDtime(Date creDtime) {
		this.creDtime = creDtime;
	}

	public Date getUpdDtime() {
		return this.updDtime;
	}

	public void setUpdDtime(Date updDtime) {
		this.updDtime = updDtime;
	}

	public Set getTzPrjNeedsSkills() {
		return this.tzPrjNeedsSkills;
	}

	public void setTzPrjNeedsSkills(Set tzPrjNeedsSkills) {
		this.tzPrjNeedsSkills = tzPrjNeedsSkills;
	}

	@Override
	public String toString() {
		return "TzPrj [prId=" + prId + ", maCustomer=" + maCustomer + ", maProjectkbn=" + maProjectkbn + ", prjKbnId="
				+ prjKbnId + ", prjImportanceId=" + prjImportanceId + ", prjTargetId=" + prjTargetId
				+ ", prjProfitabilityId=" + prjProfitabilityId + ", prjNearshoreId=" + prjNearshoreId
				+ ", prjStrategicId=" + prjStrategicId + ", prjEnduserName=" + prjEnduserName + ", prjName=" + prjName
				+ ", prjSummary=" + prjSummary + ", prjWorkingPlace=" + prjWorkingPlace + ", prjDeliveryDate="
				+ prjDeliveryDate + ", prjSecurityRequirements=" + prjSecurityRequirements + ", prjEtcRequirements="
				+ prjEtcRequirements + ", prjEtc=" + prjEtc + ", prjSalesKaishaId=" + prjSalesKaishaId
				+ ", prjAddUserId=" + prjAddUserId + ", prjUpdKaishaId=" + prjUpdKaishaId + ", prjUpdUserId="
				+ prjUpdUserId + ", creDtime=" + creDtime + ", updDtime=" + updDtime + ", tzPrjNeedsSkills="
				+ tzPrjNeedsSkills + "]";
	}

	
}
