// default package
// Generated Jun 15, 2016 5:39:06 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * TzPrjNeedsSkillId generated by hbm2java
 */
public class TzPrjNeedsSkillId implements java.io.Serializable {
	private static final Logger log = LogManager.getLogger(TzPrjNeedsSkillId.class);	
	
	private Integer prjId;
	private Integer prjSubId;
	private Integer tzPrjNeedsEngineerkbnId;

	public TzPrjNeedsSkillId() {
	}

	public TzPrjNeedsSkillId(Integer prjId, Integer prjSubId, Integer tzPrjNeedsEngineerkbnId) {
		this.prjId = prjId;
		this.prjSubId = prjSubId;
		this.tzPrjNeedsEngineerkbnId = tzPrjNeedsEngineerkbnId;
	}

	public Integer getPrjId() {
		return this.prjId;
	}

	public void setPrjId(Integer prjId) {
		this.prjId = prjId;
	}

	public Integer getPrjSubId() {
		return this.prjSubId;
	}

	public void setPrjSubId(Integer prjSubId) {
		this.prjSubId = prjSubId;
	}

	public Integer getTzPrjNeedsEngineerkbnId() {
		return this.tzPrjNeedsEngineerkbnId;
	}

	public void setTzPrjNeedsEngineerkbnId(Integer tzPrjNeedsEngineerkbnId) {
		this.tzPrjNeedsEngineerkbnId = tzPrjNeedsEngineerkbnId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TzPrjNeedsSkillId))
			return false;
		TzPrjNeedsSkillId castOther = (TzPrjNeedsSkillId) other;

		return (this.getPrjId() == castOther.getPrjId()) && (this.getPrjSubId() == castOther.getPrjSubId())
				&& (this.getTzPrjNeedsEngineerkbnId() == castOther.getTzPrjNeedsEngineerkbnId());
	}
	
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPrjId();
		result = 37 * result + this.getPrjSubId();
		result = 37 * result + this.getTzPrjNeedsEngineerkbnId();
		log.debug("============hashcode in TzPrjNeedsSkillId returns: "+result);
		return result;
	}

}
