// default package
// Generated Jun 15, 2016 5:39:06 PM by Hibernate Tools 5.1.0.Alpha1
package co.jp.eureka.entities;
/**
 * TzPrjNeedsEngineerId generated by hbm2java
 */
public class TzPrjNeedsEngineerId implements java.io.Serializable {

	private Integer prjId;
	private Integer prjSubId;
	private Integer prjNeedsEngineerkbnId;

	public TzPrjNeedsEngineerId() {
	}

	public TzPrjNeedsEngineerId(Integer prjId, Integer prjSubId, Integer prjNeedsEngineerkbnId) {
		this.prjId = prjId;
		this.prjSubId = prjSubId;
		this.prjNeedsEngineerkbnId = prjNeedsEngineerkbnId;
	}

	public Integer getPrjId() {
		return this.prjId;
	}

	public void setPrjId(Integer prjId) {
		this.prjId = prjId;
	}

	public Integer getPrjSubId() {
		return this.prjSubId;
	}

	public void setPrjSubId(Integer prjSubId) {
		this.prjSubId = prjSubId;
	}

	public Integer getPrjNeedsEngineerkbnId() {
		return this.prjNeedsEngineerkbnId;
	}

	public void setPrjNeedsEngineerkbnId(Integer prjNeedsEngineerkbnId) {
		this.prjNeedsEngineerkbnId = prjNeedsEngineerkbnId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TzPrjNeedsEngineerId))
			return false;
		TzPrjNeedsEngineerId castOther = (TzPrjNeedsEngineerId) other;

		return (this.getPrjId() == castOther.getPrjId()) && (this.getPrjSubId() == castOther.getPrjSubId())
				&& (this.getPrjNeedsEngineerkbnId() == castOther.getPrjNeedsEngineerkbnId());
	}

	@Override
	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getPrjId();
		result = 37 * result + this.getPrjSubId();
		result = 37 * result + this.getPrjNeedsEngineerkbnId();
		return result;
	}

}
